// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func InitializeServer() (*Server, error) {
	dsn := ProvideDSN()
	mainDatabase, err := NewDatabase(dsn)
	if err != nil {
		return nil, err
	}
	mainUserService := NewUserService(mainDatabase)
	port := ProvidePort()
	server := NewServer(mainUserService, port)
	return server, nil
}
