// Code generated by ogen, DO NOT EDIT.

package genogen

// CreateUserBadRequest is response for CreateUser operation.
type CreateUserBadRequest struct{}

func (*CreateUserBadRequest) createUserRes() {}

// CreateUserCreated is response for CreateUser operation.
type CreateUserCreated struct{}

func (*CreateUserCreated) createUserRes() {}

// CreateUserInternalServerError is response for CreateUser operation.
type CreateUserInternalServerError struct{}

func (*CreateUserInternalServerError) createUserRes() {}

// GetUserByIdInternalServerError is response for GetUserById operation.
type GetUserByIdInternalServerError struct{}

func (*GetUserByIdInternalServerError) getUserByIdRes() {}

// GetUserByIdNotFound is response for GetUserById operation.
type GetUserByIdNotFound struct{}

func (*GetUserByIdNotFound) getUserByIdRes() {}

// GetUsersBadRequest is response for GetUsers operation.
type GetUsersBadRequest struct{}

func (*GetUsersBadRequest) getUsersRes() {}

// GetUsersInternalServerError is response for GetUsers operation.
type GetUsersInternalServerError struct{}

func (*GetUsersInternalServerError) getUsersRes() {}

// NewOptNilInt32 returns new OptNilInt32 with value set to v.
func NewOptNilInt32(v int32) OptNilInt32 {
	return OptNilInt32{
		Value: v,
		Set:   true,
	}
}

// OptNilInt32 is optional nullable int32.
type OptNilInt32 struct {
	Value int32
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilInt32 was set.
func (o OptNilInt32) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilInt32) Reset() {
	var v int32
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilInt32) SetTo(v int32) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsSet returns true if value is Null.
func (o OptNilInt32) IsNull() bool { return o.Null }

// SetNull sets value to null.
func (o *OptNilInt32) SetToNull() {
	o.Set = true
	o.Null = true
	var v int32
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilInt32) Get() (v int32, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilInt32) Or(d int32) int32 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/User
type User struct {
	ID    string      `json:"id"`
	Name  string      `json:"name"`
	Email string      `json:"email"`
	Age   OptNilInt32 `json:"age"`
}

// GetID returns the value of ID.
func (s *User) GetID() string {
	return s.ID
}

// GetName returns the value of Name.
func (s *User) GetName() string {
	return s.Name
}

// GetEmail returns the value of Email.
func (s *User) GetEmail() string {
	return s.Email
}

// GetAge returns the value of Age.
func (s *User) GetAge() OptNilInt32 {
	return s.Age
}

// SetID sets the value of ID.
func (s *User) SetID(val string) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *User) SetName(val string) {
	s.Name = val
}

// SetEmail sets the value of Email.
func (s *User) SetEmail(val string) {
	s.Email = val
}

// SetAge sets the value of Age.
func (s *User) SetAge(val OptNilInt32) {
	s.Age = val
}

func (*User) getUserByIdRes() {}

type Users []User

func (*Users) getUsersRes() {}
