// Code generated by ogen, DO NOT EDIT.
package genogen

type CreateUserRes interface {
	createUserRes()
}

type GetEmployeesRes interface {
	getEmployeesRes()
}

type GetUserByIdRes interface {
	getUserByIdRes()
}

type GetUsersRes interface {
	getUsersRes()
}
