// Code generated by ogen, DO NOT EDIT.

package genogen

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// GetEmployeesParams is parameters of getEmployees operation.
type GetEmployeesParams struct {
	// ID of employee to return.
	EmployeeID string
}

func unpackGetEmployeesParams(packed middleware.Parameters) (params GetEmployeesParams) {
	{
		key := middleware.ParameterKey{
			Name: "employee_id",
			In:   "path",
		}
		params.EmployeeID = packed[key].(string)
	}
	return params
}

func decodeGetEmployeesParams(args [1]string, argsEscaped bool, r *http.Request) (params GetEmployeesParams, _ error) {
	// Decode path: employee_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "employee_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.EmployeeID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "employee_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetUserByIdParams is parameters of getUserById operation.
type GetUserByIdParams struct {
	// ID of user to return.
	UserID string
}

func unpackGetUserByIdParams(packed middleware.Parameters) (params GetUserByIdParams) {
	{
		key := middleware.ParameterKey{
			Name: "user_id",
			In:   "path",
		}
		params.UserID = packed[key].(string)
	}
	return params
}

func decodeGetUserByIdParams(args [1]string, argsEscaped bool, r *http.Request) (params GetUserByIdParams, _ error) {
	// Decode path: user_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "user_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.UserID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "user_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
