name: Go fix

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  modules:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.list.outputs.matrix }}
    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: List Go modules
        id: list
        run: |
          echo -n 'matrix=' >> "$GITHUB_OUTPUT"
          find . -name go.mod -exec dirname {} \; | sort | jq -c -R -s 'split("\n") | map(select(length > 0))' >> "$GITHUB_OUTPUT"

  go-fix:
    needs: modules
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module: ${{ fromJson(needs.modules.outputs.matrix) }}
    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: ${{ matrix.module }}/go.mod
          cache-dependency-path: ${{ matrix.module }}/go.*
      - name: Check go fix
        run: go fix -diff ./...
        working-directory: ${{ matrix.module }}
