name: Gotestsum Test & Coverage Summary

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  testsum:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: test/coverage/go.mod
          cache-dependency-path: test/coverage
      - name: Run tests with gotestsum
        run: |
          go tool gotestsum --junitfile report.xml --format testdox  --jsonfile tmp.json.log   --post-run-command "bash -c '
            echo; echo Slowest tests;
            go tool gotestsum tool slowest --num 10 --jsonfile tmp.json.log'" -- -coverprofile=coverage.out ./...
        working-directory: test/coverage
      - name: Test Report Summary
        if: success() || failure()
        uses: dorny/test-reporter@a43b3a5f7366b97d083190328d2c652e1a8b6aa2 # v3.0.0
        with:
          name: Tests
          path: "test/coverage/*.xml"
          reporter: java-junit
